function unout = ds(un,niter, b, r, dt,c)
%% iterates the three D matrix un niter diffusion steps forward in time
for n = 1:niter,        %%loop over the desired time-steps (Xu Prince 1998 p.363
    %disp(['Iteration : ' num2str(n)]);

    unp1 = (1-b.*dt).*un+ r.*(  circshift(un,[-1  0  0])...
                              + circshift(un,[ 1  0  0])...
                              + circshift(un,[ 0 -1  0] )...
                              + circshift(un,[ 0  1  0] )...
                              + circshift(un,[ 0  0 -1] )...
                              + circshift(un,[ 0  0  1])...
                              - 6.*un)...
                              + c.*dt;
    un = unp1;
end
unout = un;